services:
    postgres:
      image: postgres:17
      restart: unless-stopped
      container_name: postgres
      hostname: postgres
      volumes:
        - ./data/pg_data/postgres:/var/lib/postgresql/data
        - ./initdb:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - ${POSTGRES_PORT}:5432
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 15s
        timeout: 5s
        retries: 5
      networks:
        - trino-network

    minio:
      image: quay.io/minio/minio
      container_name: minio
      hostname: minio
      env_file:
        - .env
      ports:
        - 9000:9000
        - 9001:9001
      volumes:
        - ./data/minio_data:/data
      command: server /data --console-address ":9001"
      networks:
        - trino-network

    hive-metastore:
      image: starburstdata/hive:3.1.2-e.18
      container_name: hive-metastore
      hostname: hive-metastore
      depends_on:
        - postgres
      ports:
        - "9083:9083"
      environment:
        HIVE_METASTORE_DRIVER: org.postgresql.Driver 
        HIVE_METASTORE_JDBC_URL: jdbc:postgresql://postgres:5432/${HIVE_DATABASE}
        HIVE_METASTORE_USER: ${HIVE_USER}
        HIVE_METASTORE_PASSWORD: ${HIVE_PASSWORD}
        HIVE_METASTORE_WAREHOUSE_DIR: s3://hive/
        S3_ENDPOINT: http://minio:9000/
        S3_ACCESS_KEY: ${MINIO_ACCESS_KEY}
        S3_SECRET_KEY: ${MINIO_SECRET_KEY}
        S3_PATH_STYLE_ACCESS: "true"
        S3_ENDPOINT_SSL_ENABLED: "false"
        HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
        REGION: ""
        GOOGLE_CLOUD_KEY_FILE_PATH: ""
        AZURE_ADL_CLIENT_ID: ""
        AZURE_ADL_CREDENTIAL: ""
        AZURE_ADL_REFRESH_URL: ""
        AZURE_ABFS_STORAGE_ACCOUNT: ""
        AZURE_ABFS_ACCESS_KEY: ""
        AZURE_WASB_STORAGE_ACCOUNT: ""
        AZURE_ABFS_OAUTH: ""
        AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
        AZURE_ABFS_OAUTH_CLIENT_ID: ""
        AZURE_ABFS_OAUTH_SECRET: ""
        AZURE_ABFS_OAUTH_ENDPOINT: ""
        AZURE_WASB_ACCESS_KEY: ""
      networks:
        - trino-network        

    trino-coordinator:
      image: trinodb/trino:latest
      container_name: trino
      depends_on:
        - hive-metastore
      ports:
        - "18080:8080"
      volumes:
        - ./etc/trino/catalog:/etc/trino/catalog
      networks:
        - trino-network

networks:
  trino-network:
    driver: bridge        
