services:
  postgres:
    image: postgres:15
    container_name: auth_service_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./source:/source
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase_migrations
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./changelog.xml:/liquibase/changelog.xml
      - ./migrations:/liquibase/migrations
    command:
      [
        "update",
        "--changelog-file=changelog.xml",
        "--url=jdbc:postgresql://postgres:5432/${DB_NAME}",
        "--username=${DB_USER}",
        "--password=${DB_PASSWORD}"
      ]
  auth_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_app
    depends_on:
      postgres:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/app
    restart: unless-stopped
volumes:
  pgdata: