online_store:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: "{{ env_var('POSTGRES_USER', 'user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'password') }}"
      dbname: backend
      schema: analytics
      threads: 4
      keepalives_idle: 0