#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $HIVE_USER WITH PASSWORD '$HIVE_PASSWORD';
	CREATE DATABASE $HIVE_DATABASE WITH OWNER $HIVE_USER;
	GRANT ALL PRIVILEGES ON DATABASE $HIVE_DATABASE TO $HIVE_USER;
EOSQL